env = Environment()

env.Program(target='testVariant', source=['testVariant.cpp'])
env.Program(target='testParser', source=['testParser.cpp'])
env.Program(target='testTemplate', source=['testTemplate.cpp'])
env.Program(target='testTokenizer', source=['testTokenizer.cpp'])

env.Append(CCFLAGS = ['-g'])
env.Append(CPPPATH = ['../'])
env.Append(LIBPATH = ['../'])
env.Append(LIBS = ['gtest_main', 'cjango', 'gtest'])
env.Append(LINKFLAGS = ['-Wl,--rpath,../'])

